messy but fix soon. busy rn

diff --git a/Main/ripple b/Main/ripple
--- a/Main/ripple
+++ b/Main/ripple
@@ -1,5 +1,7 @@
 #!/bin/sh
 # shellcheck source=/dev/null
+# USING: APT, UNIX or GNU/Linux, Mysql Database.
+
 : '
 -------------------------------------------------------------------------------------
 |  Created by Angel Uniminin <uniminin@zoho.com> in 2019 under the terms of AGPLv3  |
@@ -17,7 +19,7 @@ die() {
 }
 
 ## WARNING ##
-die 1 "Script Under Development! Execution of arguments are disabled in development mode."
+# die 1 "Script Under Development! Execution of any arguments are disabled in development mode."
 
 notice() {
 	case "$1" in
@@ -44,7 +46,7 @@ nproc_detector() {
 			case "$LANG" in
 				en-*|*) eerror "Command 'nproc' does not return an expected value on this system, setting the processor count on '1' which will negatively affect performance on systems with more then one thread"
 			esac
-			#FIXME: using export is a horrible idea? Find better way to work with this logic
+
 			export procNum="1"
 	esac
 }
@@ -82,8 +84,8 @@ python3_5() {
 	fi
 
 	(	
-		if [ ! -f "/usr/src/Python-3.5.9.tar.xz" ]; then
-			cd /usr/src/ || die 1 "Failed to cd into '/usr/src'"
+		if [ -d "/usr/src" ]; then
+			cd /usr/src || die 1 "Failed to cd into '/usr/src'"
 			wget https://www.python.org/ftp/python/3.5.9/Python-3.5.9.tar.xz -O "Python-3.5.9.tar.xz" || die 1 "Could not download file: Python-3.5.9.tar.xz"
 		fi
 
@@ -127,8 +129,8 @@ python3_6() {
 	fi
 
 	(
-		if [ ! -f "Python-3.6.8.tar.xz" ]; then
-			cd /usr/src/ || die 1 "Failed to cd into '/usr/src'"
+		if [ -d "/usr/src" ]; then
+			cd /usr/src || die 1 "Failed to cd into '/usr/src'"
 			wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tar.xz -O "Python-3.6.8.tar.xz" || die 1 "Could not download file: Python-3.6.8.tar.xz"
 		fi
 
@@ -162,13 +164,17 @@ golang() {
 	fi
 
 	(	
-		if [ ! -f "/usr/src/go1.13.3.linux-amd64.tar.gz" ]; then
+		if [ -d "/usr/src" ]; then
 			cd /usr/src || die 1 "Failed to cd into '/usr/src'"
 			wget https://dl.google.com/go/go1.13.11.linux-amd64.tar.gz
-			tar -C /usr/local -xzf go1.13.11.linux-amd64.tar.gz
-			export PATH=$PATH:/usr/local/go/bin
-			source "$HOME"/.profile
-			export GOPATH=/root/go
+			if [ -d "/usr/local" ]; then
+				tar -C /usr/local -xzf go1.13.11.linux-amd64.tar.gz
+				export PATH=$PATH:/usr/local/go/bin
+				source "$HOME"/.profile
+				export GOPATH=/root/go
+			else
+				die 1 "Directory: '/usr/local' doesn't exist!"
+			fi
 		fi
 	)
 }
@@ -333,6 +339,10 @@ necessary_inputs() {
 # Database is required to access, read, write & manage all the user's data. (Required for all Ripple's Softwares i.e lets, peppy..)
 mysql_database() {
 
+	if command -v ping 1>/dev/null; then
+		ping -i 0.5 -c 5 raw.githubusercontent.com || die 1 "Domain: raw.githubusercontent.com is not reachable from this environment."
+	fi
+
 	task="MySQL Database"
 
 	printf "%s\n" "Setting up $task" 
@@ -357,7 +367,40 @@ mysql_database() {
 }
 
 nginx() {
-	# FIXME-Config
+
+	task="nginx"
+	pkill -f nginx
+
+
+	printf "%s\n" "Setting up $task"
+
+	if [ -d "/etc/nginx" ]; then
+		cd /etc/nginx/
+		rm -rf nginx.conf
+		wget -O nginx.conf https://raw.githubusercontent.com/Uniminin/Ripple-Auto-Installer/master/Nginx/N1.conf
+		sed -i 's#include /root/ripple/nginx/*.conf\*#include '$directory'/nginx/*.conf#' /etc/nginx/nginx.conf || die 1 "Failed to Setup Config file."
+	fi
+	if [ -d "$directory" ]; then
+		cd "$directory" || die 1 "Failed to cd into $directory"
+		mkdir nginx ; cd nginx
+
+		wget -O nginx.conf https://raw.githubusercontent.com/Uniminin/Ripple-Auto-Installer/master/Nginx/N2.conf
+		if [ -f "nginx.conf" ]; then
+			sed -Ei 's#DOMAIN#'$domain'#g; s#DIRECTORY#'$directory'#g' nginx.conf || die 1 "Failed to Setup Config file."
+		fi
+
+		wget -O old-frontend.conf https://raw.githubusercontent.com/Uniminin/Ripple-Auto-Installer/master/Nginx/old-frontend.conf
+		if [ -f "old-frontend.conf" ]; then
+			sed -Ei 's#DOMAIN#'$domain'#g; s#DIRECTORY#'$directory'#g' old-frontend.conf || die 1 "Failed to Setup Config file."
+		fi
+
+		# Using osuthailand certificate. (since plebs)
+		wget -O cert.pem https://raw.githubusercontent.com/osuthailand/ainu-certificate/master/cert.pem
+		wget -O key.pem https://raw.githubusercontent.com/osuthailand/ainu-certificate/master/key.key
+
+		nginx || die 1 "Nginx: BAD CONFIG!"
+		printf "%s\n" "Done setting up $task!" 
+	fi
 }
 
 SSL() {
@@ -373,7 +416,7 @@ SSL() {
 		git clone https://github.com/Neilpang/acme.sh
 		if [ -d "acme.sh" ]; then
 			cd acme.sh || die 1 "Failed to cd into acme.sh"
-			if [ ! -f "acme.sh" ]; then
+			if [ -f "acme.sh" ]; then
 				./acme.sh --install
 				./acme.sh --issue --standalone -d $domain -d c.$domain -d i.$domain -d a.$domain -d s.$domain -d old.$domain
 
@@ -409,9 +452,9 @@ peppy () {
 			if command -v python3.5 >/dev/null; then
 				python3.5 -m pip install -r requirements.txt
 				python3.5 setup.py build_ext --inplace
-				if [ ! -f "pep.py" ]; then
+				if [ -f "pep.py" ]; then
 					python3.5 pep.py
-					if [ ! -f "config.ini" ]; then
+					if [ -f "config.ini" ]; then
 						# FIXME-Config
 					fi
 				fi
@@ -427,6 +470,11 @@ peppy () {
 }
 
 secret() {
+
+	if command -v ping 1>/dev/null; then
+		ping -i 0.5 -c 5 github.com || die 1 "Domain: github.com is not reachable from this environment."
+	fi
+
 	if [ -d "secret" ]; then
 		rm -rf secret
 		git clone https://github.com/osufx/secret
@@ -470,8 +518,10 @@ lets() {
 			# compile oppai-ng to make pp calculation working
 			if [ -d "pp/oppai-ng" ]; then
 				(
-				cd pp/oppai-ng/ || die 1 "Failed to cd into 'pp/oppai-ng'"
-				chmod +x build ; ./build
+					if [ -f "build" ]; then
+						cd pp/oppai-ng/ || die 1 "Failed to cd into 'pp/oppai-ng'"
+						chmod +x build ; ./build
+					fi
 				)
 			fi
 			printf "%s\n" "Done Setting Up $task" 
@@ -497,10 +547,25 @@ hanayo() {
 		if [ -d "$directory" ]; then
 			go get zxq.co/ripple/hanayo
 			if [ -d "/root/go/src/zxq.co/ripple/hanayo" ]; then
-				cd /root/go/src/zxq.co/ripple/hanayo || die 1 "Failed to cd into '$task'" ; go build ; ./hanayo
-				if [ ! -f "hanayo.conf" ]; then
-					# FIXME-Config
+				cd /root/go/src/zxq.co/ripple/hanayo || die 1 "Failed to cd into '$task'"
+				go build ; ./hanayo ; ./hanayo
+				if [ -f "hanayo.conf" ]; then
+					sed -Ei "s/ListenTo=:45221/ListenTo=127.0.0.1:45221/g" hanayo.conf || die 1 "Failed to Setup Config file."
+					sed -E -i -e 'H;1h;$!d;x' hanayo.conf -e 's#DSN=#DSN='$mysql_user':'$mysql_password'@/'$database_name'#' || die 1 "Failed to Setup Config file."
+					sed -Ei "s:^RedisEnable=.*$:RedisEnable=true:g" hanayo.conf || die 1 "Failed to Setup Config file."
+					sed -Ei "s/ripple.moe/$domain/g" hanayo.conf || die 1 "Failed to Setup Config file."
+					sed -Ei "s:^APISecret=.*$:APISecret=$api_secret:g" hanayo.conf || die 1 "Failed to Setup Config file."
+					sed -Ei "s:^MainRippleFolder=.*$:MainRippleFolder=$directory:g" hanayo.conf || die 1 "Failed to Setup Config file."
+					sed -Ei "s:^AvatarsFolder=.*$:AvatarsFolder=$directory/nginx/avatar-server/Avatars:g" hanayo.conf || die 1 "Failed to Setup Config file."
+					sed -Ei "s#https://storage.$domain/api#'https://storage.ripple.moe/api'#g" hanayo.conf || die 1 "Failed to Setup Config file."
+				else
+					die 1 "Failed To Configure $task"
 				fi
+
+				if [ -f "templates/navbar.html" ]; then
+					sed -Ei 's#ripple.moe#'$domain'#' templates/navbar.html
+				fi
+
 				if [ ! -d "$directory/hanayo" ]; then
 					mv go/src/zxq.co/ripple/hanayo "$directory"
 					printf "%s\n" "Done Setting Up $task!" 
@@ -530,11 +595,15 @@ rippleapi() {
 	printf "%s\n" "Cloning & Setting up $task." 
 	(
 		if [ -d "$directory" ]; then
-			go get -u zxq.co/ripple/rippleapi
-			cd go/src/zxq.co/ripple/rippleapi || die 1 "Failed to cd into '$task'" ; go build ; ./rippleapi
+			go get zxq.co/ripple/rippleapi
+			cd go/src/zxq.co/ripple/rippleapi || die 1 "Failed to cd into '$task'"
+			go build ; ./rippleapi
 			if [ ! -f "api.conf" ]; then
-				# FIXME-Config
+				sed -E -i -e 'H;1h;$!d;x' api.conf -e 's#DSN=#DSN='$mysql_user':'$mysql_password'@/'$database_name'#' || die 1 "Failed to Setup Config file."
+				sed -Ei "s:^HanayoKey=.*$:HanayoKey=$api_secret:g" api.conf || die 1 "Failed to Setup Config file."
+				sed -Ei "s:^OsuAPIKey=.*$:OsuAPIKey=$cikey:g" api.conf || die 1 "Failed to Setup Config file."
 			fi
+
 			if [ ! -d "$directory/rippleapi" ]; then
 				mv go/src/zxq.co/ripple/rippleapi "$directory"
 				printf '%s/n' "Done setting up $task!" 
@@ -581,7 +650,8 @@ avatar_server() {
 old_frontend() {
 
 	if command -v ping 1>/dev/null; then
-		ping -i 0.5 -c 5 github.com || die 1 "Domain: github.com is not reachable from this environment."
+		ping -i 0.5 -c 5 zxq.co || die 1 "Domain: zxq.co is not reachable from this environment."
+		ping -i 0.5 -c 5 getcomposer.org || die 1 "Domain: getcomposer.org is not reachable from this environment."
 	fi
 
 	task="old-frontend"
@@ -590,19 +660,22 @@ old_frontend() {
 	(
 		if [ ! -d "/var/www/" ]; then
 			mkdir /var/www/ ; cd /var/www/ || die 1 "Could not cd into '/var/www/'"
-			git clone https://github.com/osuripple/old-frontend osu.ppy.sh
+			git clone https://zxq.co/ripple/old-frontend osu.ppy.sh
 			if [ -d "osu.ppy.sh" ]; then
 				cd osu.ppy.sh || die 1 "Failed to cd into 'osu.ppy.sh'"
 				curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
 				(
 					cd inc || die 1 "Failed to cd into 'inc'"
-					# FIXME: Automate configuration
 					cp config.sample.php config.php
 
-					if [ ! -f "config.php" ]; then
-						# FIXME-Config
+					if [ -f "config.php" ]; then
+						sed -Ei "s/root/$mysql_user/g" config.php || die 1 "Failed to Setup Config file."
+						sed -Ei "s/meme/$mysql_password/g" config.php || die 1 "Failed to Setup Config file."
+						sed -Ei "s/allora/$database_name/g" config.php || die 1 "Failed to Setup Config file."
+						sed -Ei "s/ripple.moe/$domain/g" config.php || die 1 "Failed to Setup Config file."
 					fi
 				)
+
 				composer install
 				secret
 
@@ -615,9 +688,7 @@ old_frontend() {
 
 }
 
-# FIXME: Re-Check Dependencies?
-# FIXME: change logic/implementation of logic function
-# script --all to start the entire process at once | script --help to Execute help
+
 while [ "$#" -ge 0 ]; do case "$1" in
 	--all)
 		checkRoot
